name "localoverride"
maintainer "Crowbar Project"
maintainer_email "crowbar@googlegroups.com"
license "Apache 2.0"
description "Utility cookbook to override templates"
long_description "Utility cookbook to override templates"
version "0.0.1"
